baseurl = "https://jpalczewski.github.io/"
languageCode = "pl"
title = "jpalczewski blog"
theme = "hugo-redlounge"
pygmentsstyle = "lovelace"
DefaultContentLanguage = "pl"
enableRobotsTXT = true
defaultLayout = "posts"

date_format = "2006-01-02"


[author]
	name = "Jacek Palczewski"

[indexes]
    category = "categories"
    tag = "tags"


[Params]
    gaid="UA-64805347-2"
    author = "Jacek Palczewski"
    sidebartitle = "jpalczewski's blog"


[[menu.main]]
    name = "Blog(PL)"
    url = "/posts"
    identifier = "blog-pl"
    weight = 10
[[menu.main]]
    name = "Blog(EN)"
    url = "/en/posts"
    identifier = "blog-en"
    weight = 20

#about/hallflame - 30, 40

[[menu.main]]
		name = "Homepage(PL)"
		url = "http://mion.elka.pw.edu.pl/~jpalczew/"
		identifier = "homepage"
		weight = 50


[[menu.social]]
    pre = "<i class='fa fa-github'></i>"
    url = "https://github.com/jpalczewski"
    identifier = "github"

[Languages]
[Languages.pl]
sidebartagline = "Zażółć gęślą jaźń."
[Languages.en]
sidebartagline = "Yellowing duck mind."
